### ISSUE TITLE
Bug: Hebrew navigation bar doesn't work 

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf-temp#43]
When you go to an articale ths side navbar changes to the Egnlish version:
Link to screenshot of the bug:
https://drive.google.com/file/d/1MfWtbp-bNYiobcZzMlDk0kjClpaoimdK/view?usp=drive_link

@danirdd92 What do you think?

**Comment by Drorka** [comment]
I think someone worked on supporting english and added this rule to the side nav component.

Both articles in the members route has "en" in their path, so it applies the english version (s**en**iors_contributions, m**en**toring_project).
This doesn't happen in the newbies article, because it doesn't have "en" anywhere in the path.

![image](https://github.com/Maakaf/maakaf-temp/assets/116891360/5f6441a9-456b-4551-bb08-d4d8c730d8cc)

**Comment by UrielOfir** [comment]
> I think someone worked on supporting english and added this rule to the side nav component.
> 
> Both articles in the members route has "en" in their path, so it applies the english version (s**en**iors_contributions, m**en**toring_project). This doesn't happen in the newbies article, because it doesn't have "en" anywhere in the path.
> 
> ![image](https://user-images.githubusercontent.com/116891360/277561315-5f6441a9-456b-4551-bb08-d4d8c730d8cc.png)

Can I assign you to fix it?
